# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E3MLH_llBwgQeRwJ1wptIYe_s6Y8u3l7
"""

#questão 1 a)
n = int(input('Digite um número'))
quadrado = n**2
print("resultado: ", quadrado)

#questão1 c)
n = int(input('Digite um número'))
resto = n % 2
print("resultado: ", resto)

#questão1 d)
n = int(input('digite um número'))
m = int(input('digite um número'))
media = (n+m)/2
print("resultado: " , media)

#questão2
a = 4*4 + 1
b = 6 +20-23
c = 3,0* 5,0 +1
d = 1/4+2
e = 29,0/7+4
f = 3/6,0-7
g = 2 / 2
h = 2 // 2
i = 4 % 2
j = ( 100 // 5 ) % 5
print(a,b,c,d,e,f,g,h,i,j)

#questão3
a = 2 < 3
b = ( 6 < 3 ) or ( 10 > 11 )
c = ((( 6 // 3 ) % 2 ) > 5 ) and ( 2 < ( 3 % 2 ) )
d = not( 2 < 3 )
print(a,b,c,d)

#questão4
a = 10
b =3
c =3 
d =4
e =4
f =2

x = ((a-(b/c)*2) / (d+(e/f)))*2
print(x)

#questão5
n= input('Digite seu nome')
print("ola", n)

#questão6)
n = int(input("Digite primeiro valor"))
n1 = int(input("Digite segundo valor"))
n2 = int(input("Digite terceiro valor"))
if(n > n1) and (n > n2):
   if (n1 > n2):
       print(n2)
       print(n1)
       print(n)
   else:
       print(n1)
       print(n2)
       print(n)
elif(n1 > n) and (n1 > n2):
   if (n > n2):
       print(n)
       print(n2)
       print(n1)
   else:
       print(n2)
       print(n)
       print(n1)
elif(n2 > n) and (n2 > n1):
   if (n > n1):
       print(n1)
       print(n)
       print(n2)
   else:
       print(n)
       print(n1)
       print(n2)

#questão7
n =int(input('Digite um número'))
if(n >= 0):
      print("número positivo")
else:
    print("número negativo")

#questão8 
n = int(input('Digite uma temperatura em c'))
k = (n + 273) 
f = n * (1,8 + 32)
print("Em kelvin" , k)
print("Em fahrenheit" , f)

#questão9
n =int(input('Digite um número'))
n1 =int(input('Digite outro número'))
if (n > n1):
    print("n é o maior número")
elif(n == n1):
    print("os números são iguais")
else:
    print("n1 é o maior número")

#questão10
n =int(input('Digite um número de 0 a 10'))
if n == 2 or n == 3 or n == 5 or n == 7 
    print("Número primo")
else:
    print("não é primo")

#questão11
a =int(input('Digite um número'))
b =int(input('Digite um número'))
c =int(input('Digite um número'))

if ( ((a + b) > c) and ((a + c) > b) and ((b + c) > a) ):  
    print("triângulo") 
else
    print("não triângulo")

#questão12
b =int(input('Digite o valor da base'))
h =int(input('Digite o valor da altura'))
a = (b * h)/2
print("A área é", a)

#questão13
a =int(input('Digite um número'))
b =int(input('Digite um número'))
c =int(input('Digite um número'))

if ( ((a + b) > c) and ((a + c) > b) and ((b + c) > a) ):  
if a == b == c: 
   print("triângulo equilátero")
elif: ((a != b) and (b != c) and (c != a)):
   print("triângulo escaleno")
else: 
   print("triângulo isósceles")

#questão14
a =int(input('Digite um ângulo'))
b =int(input('Digite um ângulo'))
c =int(input('Digite um ângulo'))

if ((a > 90) or (b > 90) or (c > 90)):
      print("triângulo obtusângulo")
elif ((a < 90) or (b < 90) or (c < 90)):
      print("triângulo acutângulo")
elif ((a == 90) or (b == 90) or (c == 90)):
      print("retângulo")

#questão15
p =int(input('Digite a potência da lâmpada'))
c =int(input('Digite o comprimento do cômodo'))
l =int(input('Digite a largura do cômodo'))
lampadas = (c * l) * 18 / p
print(lampadas)

#questâo 16
a =int(input('Digite a altura do cômodo'))
c =int(input('Digite o comprimento do cômodo'))
l =int(input('Digite a largura do cômodo'))
azulejos = (((c*a)*2 + (l*a)*2) / 1.5)
print(azulejos)

#questâo17
o =int(input('Digite o odometro no inicio do dia'))
km =int(input('Digite o odometro no final do dia'))
v =int(input('Digite o valor total recebido'))
l =int(input('Digite a quantidade de combustível gastado'))
media = (km-o)/l 
lucro = v-(1.9*l)
print(media,lucro)

#questâo18
av1 = int(input("Nota da primeira avaliação:"))
av2 = int(input("Nota da segunda avaliação:"))
opt = int(input("Nota da avaliação optativa:"))

media1 = (av1 + av2)/2
media2 = (av1 + opt)/2
media3 = (av2 + opt)/2

mediaFinal = -1

if ( (media1 > media2) and (media1 > media3) ):
  mediaFinal = media1
else:
  if (media2 > media3):
    mediaFinal = media2
  else:
    mediaFinal = media3

if (mediaFinal >= 6):
  print("Aprovado com média ",end="")
elif ( (mediaFinal >= 3) and (mediaFinal < 6) ):
  print("Exame com média ", end="")
else:
  print("Reprovado com média ",end="")

print(mediaFinal)

#questâo19
a =int(input('Digite a idade de um homem'))
b =int(input('Digite a idade de outro homem'))
c =int(input('Digite a idade de uma mulher'))
d =int(input("Digite a idade de outra mulher"))
calculo = 0
if (a > b) and (c > d):
    calculo = a + d
    print("soma do homem mais velho com a mulher mais nova:" , calculo)
else:
    calculo = b + c
    print("soma do homem mais velho com a mulher mais nova:" , calculo)
if (a > b) and (c > d):
    calculo = b * c
    print("multiplicação do homem mais novo com a mulher mais velha:" , calculo)
else:
    calculo = a * d
    print("multiplicação do homem mais novo com a mulher mais velha:" , calculo)

#questâo20
a =int(input('Digite uma frase'))
b =int(input('Digite outra frase'))
if a == b:
    print("sâo iguais")
else:
    print("sâo diferentes")